version: '3.7'

services:
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    image: pentest_serverapp:${APP_VERSION:-latest}
    hostname: api
    ports:
      - ${APP_PORT:-8000}:8000
    networks:
      - backend
    tty: true
    restart: always
    environment:
      APP_ENV: "${APP_ENV}"
    depends_on:
      - db
    volumes:
      - ./api:/home/api
      - ./app:/home/app
      - ./core:/home/core
    #command: dockerize -wait tcp://db:3306 -timeout 20s && alembic upgrade head && gunicorn --bind ${APP_HOST:-'0.0.0.0'}:${APP_PORT:-8000} -w 4 -k uvicorn.workers.UvicornWorker app.server:app --reload

  db:
    env_file:
      - .env
    image: mysql:8.0.30
    container_name: db
    hostname: db
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 3307:3306
    expose:
      - 3307
    command: [ "mysqld" ]
    restart: always
    networks:
      - backend
    volumes:
      - db_data:/volumes/db
  # redis:
  #   build:
  #     context: .
  #     dockerfile: docker/redis/Dockerfile
  #   container_name: redis
  #   hostname: redis
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - backend

networks:
  backend:
    driver: 'bridge'

volumes:
  db_data:
    name: volumes_dir