[tool.poetry]
name = "fastapi-boilerplate"
version = "0.1.0"
description = "FastAPI Boilerplate"
authors = ["Hide <padocon@naver.com>"]

[tool.poetry.dependencies]
python = "^3.11.0"
alembic = "^1.8.1"
SQLAlchemy = { extras = ["asyncio"], version = "^2.0.23" }
PyJWT = "^2.4.0"
uvicorn = "^0.18.3"
fastapi = "0.104.1"
celery = "^5.2.7"
gunicorn = "^20.1.0"
fastapi-event = "^0.1.3"
pythondi = "^1.2.4"
ujson = "^5.4.0"
aiomysql = "^0.1.1"
click = "^8.1.3"
greenlet = "1.1.3"
redis = "^4.3.4"
pydantic = "^2.5.1"
pydantic-settings = "^2.1.0"
dnspython = "^2.4.2"
autopep8 = "^2.0.4"
scapy = "^2.5.0"
requests = "^2.31.0"
validators = "^0.22.0"
tldextract = "^5.1.1"

[tool.poetry.dev-dependencies]
behave = "^1.2.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
